### ISSUE TITLE
no significant improvement for SJF vs continues batch(vllm, FCFS)

### ISSUE THREAD

**Issue by wiluen** [James-QiuHaoran/LLM-serving-with-proxy-models#12]
@James-QiuHaoran ,极好的又有创新性的工作。
我尝试在vLLM的continues batch中使用不同的调度算法，默认连续批处理（FCFS）的性能非常好。我使用SJF，没有发现任何改善。但从理论上讲，使用SJF会比FCFS具有更好的性能（可能从某个层面上），因为SJF知道输出长度。 但是我实验却无法验证。
根源在于不同的调度方法只是选取不同的seq进行处理，长seq和短seq在continues batch中似乎都有理想的位置可以放置，并且不会出现资源浪费的情况。
我真的希望收到你对这个问题的见解。

**Comment by James-QiuHaoran** [comment]
如果batch size足够大，长/短request/sequence都可以fit进来，head-of-line blocking的问题就不会出现；这个work主要针对实际情况batch size不会够大的时候（limited by memory or TBT/TTFT SLO latency）或者存在request queueing的时候，FCFS的问题才会暴露
