### ISSUE TITLE
关于不同的调度策略是如何在系统中实现的

### ISSUE THREAD

**Issue by wiluen** [James-QiuHaoran/LLM-serving-with-proxy-models#9]
感谢分享出色的工作！我有个疑惑的点：
分享的代码看起来貌似是通过simulation来进行测试的，在真实的系统中是否是提前收集了一批query在不同的执行顺序下的推理性能结果（模拟不同的调度结果）？或者是在真实的LLM系统中实现了这个基于prediction的调度器？

**Comment by James-QiuHaoran** [comment]
我们在vllm上有一个sjf简单的实现（来替换fcfs scheduler），还没release；可以参考vllm的[priority scheduling feature](https://github.com/vllm-project/vllm/issues/6077)，把sequence长度设置为priority的inverse即可
